name: CI/CD Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/noteapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/noteapp:latest

      # SSH to EC2 and redeploy
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user  # or ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/NoteApp
            sudo docker-compose pull
            sudo docker-compose up -d
